import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";

const raj = Rajdhani({weight: ["300", "400", '500', "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Games Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raj.className}>{children}</body>
    </html>
  );
}
